### ISSUE TITLE
Investigate nlohmann_json integration 

### ISSUE THREAD

**Issue by LLagu** [Open-Source-Digital-Twin/furuta-pendulum-controller#19]
When linking the target in `config/CMakeLists.txt` using 
`target_link_libraries(ConfigLib
    PRIVATE 
    nlohmann_json::nlohmann_json
    )`

the library is not correctly included:
`fatal error: 'nlohmann/json.hpp' file not found
[build] #include <nlohmann/json.hpp>`

It seems to be an access modifier issue as using PUBLIC solves the problem. But exactly why?

**Comment by caiopiccirillo** [comment]
From https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#id25 :


> Generally, a dependency should be specified in a use of [target_link_libraries()](https://cmake.org/cmake/help/latest/command/target_link_libraries.html#command:target_link_libraries) with the PRIVATE keyword if it is used by only the implementation of a library, and not in the header files. If a dependency is additionally used in the header files of a library (e.g. for class inheritance), then it should be specified as a PUBLIC dependency. A dependency which is not used by the implementation of a library, but only by its headers should be specified as an INTERFACE dependency.

**Comment by caiopiccirillo** [comment]
@LLagu I'll close this issue, since we already have it integrated.
